# Generated by Django 4.2 on 2023-05-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='users_likes',
            new_name='users_like',
        ),
    ]
